#!/bin/sh

[ -f ~/.screenlayout/work_home.sh ] && \
    xrandr --listmonitors | grep -q "DP-" && \
    ~/.screenlayout/work_home.sh

feh --bg-fill ~/Pictures/Background.png

setxkbmap -option caps:escape

picom &
dunst &
unclutter &
sxhkd &

[[ -d $HOME/scripts ]] && export PATH=$HOME/scripts:$PATH
[ -f $HOME/scripts/dwmbar ] && $HOME/scripts/dwmbar &

# Launch dwm.  If we exit or reload it, we will log out
dwm >/dev/null 2>&1
