#!/bin/bash/sh

# Set the background
feh --bg-scale ~/Pictures/background.jpg &

# Start a compositor for transparency
compton &

# Make matlab work when you spawn it
export _JAVA_AWT_WM_NONREPARENTING=1 # For matlab to work in dwm.

# Do bar updates for dwm (thanks luke smith)
[ -f ~/.config/dwm/dwmbar ] && ~/.config/dwm/dwmbar &
